# Generated by Django 5.0.4 on 2024-05-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reg',
            new_name='register_data',
        ),
    ]
