# Generated by Django 5.0.4 on 2024-06-01 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query_app', '0003_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee')], max_length=10)),
                ('query_priority', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=10)),
                ('query_title', models.CharField(max_length=50)),
                ('query_data', models.CharField(max_length=5000)),
                ('query_date', models.DateField()),
                ('query_sender', models.CharField(max_length=20)),
                ('query_status', models.CharField(max_length=20)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_app.register_data')),
            ],
        ),
        migrations.CreateModel(
            name='response_queries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_typ', models.CharField(choices=[('student', 'Student'), ('employee', 'Employee')], max_length=10)),
                ('res_priority', models.CharField(choices=[('high', 'High'), ('low', 'Low')], max_length=10)),
                ('res_title', models.CharField(max_length=50)),
                ('query_date', models.DateField()),
                ('response_data', models.CharField(max_length=5000)),
                ('resonded_date', models.DateField()),
                ('query_sender', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('res_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='query_app.register_data')),
            ],
        ),
        migrations.DeleteModel(
            name='query',
        ),
    ]
